import type { Metadata } from "next";
import "./globals.css";
// import { Providers } from "./providers/providers";



export const metadata: Metadata = {
  title: "Личный кабинет",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="ru">
      <body className="bg-white">
        {/* <Providers> */}
          <div className="flex h-screen">
            {/* Sidebar */}
            {/* <SideBar /> */}

            {/* Правая часть с Header и контентом */}
            <div className="flex-1 flex flex-col  overflow-hidden">
              {/* Header - НЕ скроллится */}
              <div className="">
                {/* <Header /> */}
              </div>

              {/* Контент - ТОЛЬКО он скроллится */}
              <main className="flex-1 overflow-y-auto ">
                {children}
              </main>
            </div>
          </div>
        {/* </Providers> */}
      </body>
    </html>
  );
}
